config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Coal Mine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Comfortaa" />

<div class="collapse bg-dark" id="navbarToggleExternalContent">
<div class="d-none d-md-block container-fluid">
    <div class="row">
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4" style="line-height: 1em;">
            <h4 class="text-white">About Me</h4>
            <p.not() class="text-muted" style="font-size:11px;">Hi there, my name is Cole. Friend group always jokes with the spelling being Coal, thus the name
            of the website. I'm a Computer Security major, love reading, Video Games, and CTFs. I used to do CyberPatriot through High School and now I help an
            old teacher with the current teams he has as a coach.
            </p>
        </div>
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4">
            <h4 class="text-white">Contact Details</h4>
            <ul class="list-unstyled">
                <li><a href="https://github.com/MidLanerST/" class="text-white">Github: MidLanerST</a></li>
                <li class="text-white">Professional Email: cole.snyder.m@gmail.com</li>
                <li class="text-white">Personal Email: midlanerplays@gmail.com</li>
                <li class="text-white">Discord: MidLanerST#7016</li>
            </ul>
        </div>
    </div>
</div>
</div>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
<a class="navbar-brand" href="/">The Coal Mine</a>


<div class="collapse navbar-collapse" id="navbarsDefault">
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="/" style="font-size:18px;">Home</a>
    </li>
        <% if !user_signed_in? %>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign In' , new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign Up' , new_user_registration_path, class: "nav-link" %>
                </li>
            <% else %>
            <li class="nav-item active" style="font-size:18px;">
                <%= link_to 'Add New Project', new_project_path, class: "nav-link" %>
            </li>
        <% end %>
</ul>


    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="d-flex justify-content-between">
            <button class="d-none d-md-block navbar-toggler" href="#collapse1" type="button"
                data-target="#navbarToggleExternalContent" data-toggle="collapse" aria-controls="navbarHeader"
                aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <% if user_signed_in? %>
    <li class="nav-item navbar-nav" style="font-size:18px;">
        <%= link_to 'My Account', edit_user_registration_path, class: "nav-link", style: "color:white;" %>
    </li>
    <li class="nav-item navbar-nav" style="font-size:18px;color=white">
        <%= link_to('Sign Out', destroy_user_session_path, class: "nav-link" , method: :delete) %>
    </li>
    <% end %>
</div>
</nav>

<div class="container2" style="margin-top:30px">
    <h1 style="text-align:center">Editing Project</h1>

    <div class="container3">
        <%= render 'form', project: @project %>
        
        <button type="button" class="btn btn-sm btn-outline-thirdary" style="color:white"><%= link_to 'Back', projects_path, class: "whitea" %></button>
        <button type="button" class="btn btn-sm btn-outline-thirdary" style="color:white"><%= link_to 'Show', @project, class:"whitea" %></button>
    </div>
</div>

app/views/projects/index.html.erb
<!-- To add somewhere #eea9c7 -->
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Comfortaa" />

<div class="collapse bg-dark" id="navbarToggleExternalContent">
<div class="d-none d-md-block container-fluid">
    <div class="row">
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4" style="line-height: 1em;">
            <h4 class="text-white">About Me</h4>
            <p.not() class="text-muted" style="font-size:11px;">Hi there, my name is Cole. Friend group always jokes with the spelling being Coal, thus the name
            of the website. I'm a Computer Security major, love reading, Video Games, and CTFs. I used to do CyberPatriot through High School and now I help an
            old teacher with the current teams he has as a coach.
            </p>
        </div>
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4">
            <h4 class="text-white">Contact Details</h4>
            <ul class="list-unstyled">
                <li><a href="https://github.com/MidLanerST/" class="text-white">Github: MidLanerST</a></li>
                <li class="text-white">Professional Email: cole.snyder.m@gmail.com</li>
                <li class="text-white">Personal Email: midlanerplays@gmail.com</li>
                <li class="text-white">Discord: MidLanerST#7016</li>
            </ul>
        </div>
    </div>
</div>
</div>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
<a class="navbar-brand" href="/">The Coal Mine</a>


<div class="collapse navbar-collapse" id="navbarsDefault">
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="/" style="font-size:18px;">Home</a>
    </li>
        <% if !user_signed_in? %>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign In' , new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign Up' , new_user_registration_path, class: "nav-link" %>
                </li>
            <% else %>
            <li class="nav-item active" style="font-size:18px;">
                <%= link_to 'Add New Project', new_project_path, class: "nav-link" %>
            </li>
        <% end %>
</ul>


    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="d-flex justify-content-between">
            <button class="d-none d-md-block navbar-toggler" href="#collapse1" type="button"
                data-target="#navbarToggleExternalContent" data-toggle="collapse" aria-controls="navbarHeader"
                aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <% if user_signed_in? %>
    <li class="nav-item navbar-nav" style="font-size:18px;">
        <%= link_to 'My Account', edit_user_registration_path, class: "nav-link", style: "color:white;" %>
    </li>
    <li class="nav-item navbar-nav" style="font-size:18px;color=white">
        <%= link_to('Sign Out', destroy_user_session_path, class: "nav-link" , method: :delete) %>
    </li>
    <% end %>
</div>
</nav>

<% if flash[:notice] or flash[:alert] %>
<br>
<center>
<p id="notice"><b><%= notice %></b></p>
<p class="alert"><b><%= alert %></b></p>
</center>
<% end %>

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Projects</h1>
    <p class="lead text-muted">Hi! Welcome to the page! Feel free to take a look around at any projects that catch your eye. You can also feel free to add your 
    own projects if you wish. Contact details and information about myself can be found in the drop down menu above. You can see all projects below.</p>
  </div>
</section>

<div class="album py-5">
  <div class="container">
    <div class="row">
    <% @projects.each do |project| %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <h1 style="margin-left: 20px; margin-top: 10px"><%= project.title %></h1>
          <div class="card-body">
            <p class="card-text" style="margin-left: 5px; overflow=hidden;"><%= project.description %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary" ><%= link_to 'View', project %></button>
                <% if user_signed_in? %>
                  <button type="button" class="btn btn-sm btn-outline-secondary" style="color:#666666" onclick="window.location.href='<%= edit_project_path(project) %>'">Edit</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>


<!--
  <h1>Projects</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
          <tr class='one'>
            <td class='mb-0'><%= project.title %></td>
            <td class='card-text mb-auto'><%= project.description %></td>
            <td><%= link_to 'Show', project %></td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Project', new_project_path %>

-->

</body>

app/views/projects/new.html.erb
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Comfortaa" />

<div class="collapse bg-dark" id="navbarToggleExternalContent">
<div class="d-none d-md-block container-fluid">
    <div class="row">
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4" style="line-height: 1em;">
            <h4 class="text-white">About Me</h4>
            <p.not() class="text-muted" style="font-size:11px;">Hi there, my name is Cole. Friend group always jokes with the spelling being Coal, thus the name
            of the website. I'm a Computer Security major, love reading, Video Games, and CTFs. I used to do CyberPatriot through High School and now I help an
            old teacher with the current teams he has as a coach.
            </p>
        </div>
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4">
            <h4 class="text-white">Contact Details</h4>
            <ul class="list-unstyled">
                <li><a href="https://github.com/MidLanerST/" class="text-white">Github: MidLanerST</a></li>
                <li class="text-white">Professional Email: cole.snyder.m@gmail.com</li>
                <li class="text-white">Personal Email: midlanerplays@gmail.com</li>
                <li class="text-white">Discord: MidLanerST#7016</li>
            </ul>
        </div>
    </div>
</div>
</div>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
<a class="navbar-brand" href="/">The Coal Mine</a>


<div class="collapse navbar-collapse" id="navbarsDefault">
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="/" style="font-size:18px;">Home</a>
    </li>
        <% if !user_signed_in? %>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign In' , new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign Up' , new_user_registration_path, class: "nav-link" %>
                </li>
            <% else %>
            <li class="nav-item active" style="font-size:18px;">
                <%= link_to 'Add New Project', new_project_path, class: "nav-link" %>
            </li>
        <% end %>
</ul>


    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="d-flex justify-content-between">
            <button class="d-none d-md-block navbar-toggler" href="#collapse1" type="button"
                data-target="#navbarToggleExternalContent" data-toggle="collapse" aria-controls="navbarHeader"
                aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <% if user_signed_in? %>
    <li class="nav-item navbar-nav" style="font-size:18px;">
        <%= link_to 'My Account', edit_user_registration_path, class: "nav-link", style: "color:white;" %>
    </li>
    <li class="nav-item navbar-nav" style="font-size:18px;color=white">
        <%= link_to('Sign Out', destroy_user_session_path, class: "nav-link" , method: :delete) %>
    </li>
    <% end %>
</div>
</nav>

<div class="container2" style="margin-top:30px">
    <h1 style="text-align:center">New Project</h1>

    <div class="container3">
        <%= render 'form', project: @project %>

        <button type="button" class="btn btn-sm btn-outline-thirdary" style="color:#666666" onclick="window.location.href='<%= projects_path%>'">Back</button>
    </div>
</div>

app/views/projects/show.html.erb
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Comfortaa" />

<div class="collapse bg-dark" id="navbarToggleExternalContent">
<div class="d-none d-md-block container-fluid">
    <div class="row">
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4" style="line-height: 1em;">
            <h4 class="text-white">About Me</h4>
            <p.not() class="text-muted" style="font-size:11px;">Hi there, my name is Cole. Friend group always jokes with the spelling being Coal, thus the name
            of the website. I'm a Computer Security major, love reading, Video Games, and CTFs. I used to do CyberPatriot through High School and now I help an
            old teacher with the current teams he has as a coach.
            </p>
        </div>
        <div class="col-2 col-sm-2 col-md-2"></div>
        <div class="col-4 col-sm-4 col-md-4">
            <h4 class="text-white">Contact Details</h4>
            <ul class="list-unstyled">
                <li><a href="https://github.com/MidLanerST/" class="text-white">Github: MidLanerST</a></li>
                <li class="text-white">Professional Email: cole.snyder.m@gmail.com</li>
                <li class="text-white">Personal Email: midlanerplays@gmail.com</li>
                <li class="text-white">Discord: MidLanerST#7016</li>
            </ul>
        </div>
    </div>
</div>
</div>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
<a class="navbar-brand" href="/">The Coal Mine</a>


<div class="collapse navbar-collapse" id="navbarsDefault">
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="/" style="font-size:18px;">Home</a>
    </li>
        <% if !user_signed_in? %>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign In' , new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item active" style="font-size:18px;">
                    <%= link_to 'Sign Up' , new_user_registration_path, class: "nav-link" %>
                </li>
            <% else %>
            <li class="nav-item active" style="font-size:18px;">
                <%= link_to 'Add New Project', new_project_path, class: "nav-link" %>
            </li>
        <% end %>
</ul>


    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="d-flex justify-content-between">
            <button class="d-none d-md-block navbar-toggler" href="#collapse1" type="button"
                data-target="#navbarToggleExternalContent" data-toggle="collapse" aria-controls="navbarHeader"
                aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <% if user_signed_in? %>
    <li class="nav-item navbar-nav" style="font-size:18px;">
        <%= link_to 'My Account', edit_user_registration_path, class: "nav-link", style: "color:white;" %>
    </li>
    <li class="nav-item navbar-nav" style="font-size:18px;color=white">
        <%= link_to('Sign Out', destroy_user_session_path, class: "nav-link" , method: :delete) %>
    </li>
    <% end %>
</div>
</nav>

<% if flash[:notice] or flash[:alert] %>
<br>
<center>
<p id="notice"><b><%= notice %></b></p>
<p class="alert"><b><%= alert %></b></p>
</center>
<% end %>

<div class="container2" style="margin-top:50px">
  <div class="container1">
    <h3 style="text-align: center"> <%= @project.title %> </h3>
  </div>

  <div class="container3">
    <h5 style="letter-spacing: 1px">
      <%= @project.description %>
    </h5>
  </div>
  
  <button type="button" class="btn btn-sm btn-outline-secondary" style="color#666666" onclick="window.location.href='<%= projects_path %>'">Back</button>
  <% if user_signed_in? %>
    <button type="button" class="btn btn-sm btn-outline-secondary" style="color:#666666" onclick="window.location.href='<%= edit_project_path(@project) %>'">Edit</button>
    <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  <% end %>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>